pipeline:
  build:
    image: golang:alpine
    environment:
      - KEY=VALUE
    secrets: [key1, key2]
    commands:
      - echo $$KEY
      - pwd
      - ls
      - go test
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
      - ./app
  publish:
    image: plugins/docker
    repo: null395922/drone-demo
    dockerfile: ./Dockerfile
    tags: latest
