pipeline:
  test:
    image: golang:1.10.2
    commands:
      - go test
  build:
    image: golang:alpine
    environment:
      - KEY=VALUE
    secrets: [key1, key2]
    commands:
      - echo $$KEY
      - pwd
      - ls
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
      - ./app
  publish:
    image: plugins/docker
    repo: null395922/demo
    username: null395922
    password: hellohello
    #dockerfile: ./Dockerfile
    tags: latest
